// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetV1Dining implements get-v1-dining operation.
//
// Returns all necessary data for BearTrak's dining section.
//
// GET /v1/dining
func (UnimplementedHandler) GetV1Dining(ctx context.Context) (r []Eatery, _ error) {
	return r, ht.ErrNotImplemented
}

// GetV1Gyms implements get-v1-gyms operation.
//
// Returns all necessary data for BearTrak's gym section.
//
// GET /v1/gyms
func (UnimplementedHandler) GetV1Gyms(ctx context.Context) (r []Gym, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
