// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	GetV1DiningOperation OperationName = "GetV1Dining"
	GetV1GymsOperation   OperationName = "GetV1Gyms"
)
