// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// GetV1Dining implements get-v1-dining operation.
	//
	// Returns all necessary data for BearTrak's dining section.
	//
	// GET /v1/dining
	GetV1Dining(ctx context.Context) ([]Eatery, error)
	// GetV1Gyms implements get-v1-gyms operation.
	//
	// Returns all necessary data for BearTrak's gym section.
	//
	// GET /v1/gyms
	GetV1Gyms(ctx context.Context) ([]Gym, error)
	// NewError creates *ErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
