// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	GetV1AlertsOperation          OperationName = "GetV1Alerts"
	GetV1DiningOperation          OperationName = "GetV1Dining"
	GetV1GymsOperation            OperationName = "GetV1Gyms"
	GetV1TransitRoutesOperation   OperationName = "GetV1TransitRoutes"
	GetV1TransitVehiclesOperation OperationName = "GetV1TransitVehicles"
)
