// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	DeleteV1DiningUserOperation          OperationName = "DeleteV1DiningUser"
	GetV1AlertsOperation                 OperationName = "GetV1Alerts"
	GetV1DiningOperation                 OperationName = "GetV1Dining"
	GetV1DiningUserOperation             OperationName = "GetV1DiningUser"
	GetV1DiningUserAccountsOperation     OperationName = "GetV1DiningUserAccounts"
	GetV1DiningUserSessionOperation      OperationName = "GetV1DiningUserSession"
	GetV1EventsOperation                 OperationName = "GetV1Events"
	GetV1GymCapacitiesOperation          OperationName = "GetV1GymCapacities"
	GetV1GymCapacityPredictionsOperation OperationName = "GetV1GymCapacityPredictions"
	GetV1GymsOperation                   OperationName = "GetV1Gyms"
	GetV1StudyOperation                  OperationName = "GetV1Study"
	GetV1TransitRoutesOperation          OperationName = "GetV1TransitRoutes"
	GetV1TransitVehiclesOperation        OperationName = "GetV1TransitVehicles"
	PostV1DiningUserOperation            OperationName = "PostV1DiningUser"
)
