// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// DeleteV1DiningUser implements deleteV1DiningUser operation.
//
// Deletes a user given a session.
//
// DELETE /v1/dining/user
func (UnimplementedHandler) DeleteV1DiningUser(ctx context.Context, params DeleteV1DiningUserParams) (r DeleteV1DiningUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetV1Alerts implements getV1Alerts operation.
//
// Returns all of BearTrak's active alerts.
//
// GET /v1/alerts
func (UnimplementedHandler) GetV1Alerts(ctx context.Context) (r []Alert, _ error) {
	return r, ht.ErrNotImplemented
}

// GetV1Dining implements getV1Dining operation.
//
// Returns all necessary data for BearTrak's dining section.
//
// GET /v1/dining
func (UnimplementedHandler) GetV1Dining(ctx context.Context) (r []Eatery, _ error) {
	return r, ht.ErrNotImplemented
}

// GetV1DiningUser implements getV1DiningUser operation.
//
// Get Information.
//
// GET /v1/dining/user
func (UnimplementedHandler) GetV1DiningUser(ctx context.Context, params GetV1DiningUserParams) (r GetV1DiningUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetV1DiningUserAccounts implements getV1DiningUserAccounts operation.
//
// Returns a dining user's transaction accounts given a session.
//
// GET /v1/dining/user/accounts
func (UnimplementedHandler) GetV1DiningUserAccounts(ctx context.Context, params GetV1DiningUserAccountsParams) (r GetV1DiningUserAccountsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetV1DiningUserSession implements getV1DiningUserSession operation.
//
// Refreshes a session given a user device.
//
// GET /v1/dining/user/session
func (UnimplementedHandler) GetV1DiningUserSession(ctx context.Context, params GetV1DiningUserSessionParams) (r GetV1DiningUserSessionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetV1Events implements getV1Events operation.
//
// Returns event data for BearTrak's events section.
//
// GET /v1/events
func (UnimplementedHandler) GetV1Events(ctx context.Context) (r []Event, _ error) {
	return r, ht.ErrNotImplemented
}

// GetV1GymCapacities implements getV1GymCapacities operation.
//
// Returns all time-logged gym capacity data.
//
// GET /v1/gyms/capacities
func (UnimplementedHandler) GetV1GymCapacities(ctx context.Context) (r []GymCapacityData, _ error) {
	return r, ht.ErrNotImplemented
}

// GetV1GymCapacityPredictions implements getV1GymCapacityPredictions operation.
//
// Returns all time-logged gym capacity prediction data.
//
// GET /v1/gyms/capacities/predictions
func (UnimplementedHandler) GetV1GymCapacityPredictions(ctx context.Context) (r []GymCapacityPredictions, _ error) {
	return r, ht.ErrNotImplemented
}

// GetV1Gyms implements getV1Gyms operation.
//
// Returns all necessary data for BearTrak's gym section.
//
// GET /v1/gyms
func (UnimplementedHandler) GetV1Gyms(ctx context.Context) (r []Gym, _ error) {
	return r, ht.ErrNotImplemented
}

// GetV1Study implements getV1Study operation.
//
// Returns all necessary data for BearTrak's study section.
//
// GET /v1/study
func (UnimplementedHandler) GetV1Study(ctx context.Context) (r *StudyData, _ error) {
	return r, ht.ErrNotImplemented
}

// GetV1TransitRoutes implements getV1TransitRoutes operation.
//
// Returns non time-sensitive, route-related data for BearTrak's transit section.
//
// GET /v1/transit/routes
func (UnimplementedHandler) GetV1TransitRoutes(ctx context.Context) (r []BusRoute, _ error) {
	return r, ht.ErrNotImplemented
}

// GetV1TransitVehicles implements getV1TransitVehicles operation.
//
// Returns time-sensitive, vehicle-related data for BearTrak's transit section.
//
// GET /v1/transit/vehicles
func (UnimplementedHandler) GetV1TransitVehicles(ctx context.Context) (r []Vehicle, _ error) {
	return r, ht.ErrNotImplemented
}

// PostV1DiningUser implements postV1DiningUser operation.
//
// Registers a new user given a device and session.
//
// POST /v1/dining/user
func (UnimplementedHandler) PostV1DiningUser(ctx context.Context, params PostV1DiningUserParams) (r PostV1DiningUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
