// Code generated by ogen, DO NOT EDIT.
package api

type DeleteV1DiningUserRes interface {
	deleteV1DiningUserRes()
}

type GetV1DiningUserAccountsRes interface {
	getV1DiningUserAccountsRes()
}

type GetV1DiningUserBarcodeRes interface {
	getV1DiningUserBarcodeRes()
}

type GetV1DiningUserSessionRes interface {
	getV1DiningUserSessionRes()
}

type PostV1DiningUserRes interface {
	postV1DiningUserRes()
}
