// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DiningUser struct {
	ID            int32
	DeviceID      string
	UserID        string
	CreatedAt     pgtype.Timestamp
	LastSessionAt pgtype.Timestamp
}

type GymCapacity struct {
	ID            int32
	LocationID    int32
	Percentage    int32
	LastUpdatedAt pgtype.Timestamptz
}
