// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// GetV1Alerts implements getV1Alerts operation.
	//
	// Returns all of BearTrak's active alerts.
	//
	// GET /v1/alerts
	GetV1Alerts(ctx context.Context) ([]Alert, error)
	// GetV1Dining implements getV1Dining operation.
	//
	// Returns all necessary data for BearTrak's dining section.
	//
	// GET /v1/dining
	GetV1Dining(ctx context.Context) ([]Eatery, error)
	// GetV1Gyms implements getV1Gyms operation.
	//
	// Returns all necessary data for BearTrak's gym section.
	//
	// GET /v1/gyms
	GetV1Gyms(ctx context.Context) ([]Gym, error)
	// GetV1TransitRoutes implements getV1TransitRoutes operation.
	//
	// Returns non time-sensitive, route-related data for BearTrak's transit section.
	//
	// GET /v1/transit/routes
	GetV1TransitRoutes(ctx context.Context) ([]BusRoute, error)
	// GetV1TransitVehicles implements getV1TransitVehicles operation.
	//
	// Returns time-sensitive, vehicle-related data for BearTrak's transit section.
	//
	// GET /v1/transit/vehicles
	GetV1TransitVehicles(ctx context.Context) ([]Vehicle, error)
	// NewError creates *ErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
